### ISSUE TITLE
Chrome 55 bug

### ISSUE THREAD

**Issue by jswing-mie** [vistaprint/PointyJS#5]
Chrome 55 (released late Nov 2016) did not support the w3c's spec for navigator.pointerEnabled.  I made this change to my copy and thought you might want to add it too.
```
-        pointer: !! (navigator.pointerEnabled || navigator.msPointerEnabled)
+        pointer: !! (navigator.pointerEnabled || navigator.msPointerEnabled || window.PointerEvent)
```

**Comment by labaneilers** [comment]
Thank you! This has been working fine for so long, I almost thought I was off the hook for maintenance :(
Fixed with: https://github.com/vistaprint/PointyJS/commit/3f31baec45b59ad0c4efb5bc3286e9589d102b57
